version: '3'

services:
  php:
    container_name: PHP7
    build: .
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./html:/var/www/html
    - ./customphp.ini:/usr/local/etc/php/php.ini
